version: '3.8'

services:
  product-api:
    build:
      context: ./product-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=sqlite
      - DB_PATH=/app/data/products.db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network

  product-frontend:
    build:
      context: ./product-frontend-nextjs
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080/api
    depends_on:
      product-api:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge